### ISSUE TITLE
Connecting Pryv to Moves fails

### ISSUE THREAD

**Issue by skoneka** [pryv/bridge-moves#1]
After entering the PIN in Moves app, Pryv fails to connect to Moves. Some problem with the token

https://bridges.pryv.io:7443/auth/moves/callback?code=agdA5rdt4CvD12xRScx683HC69rpZ8heJ8cNr3761eyM0Xr3R9SOm8pn2NpV0Ef3&state=

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by kschiess** [comment]
Hi Artur, 

Sorry for the delay in answering this. Is this still an issue for you? 

Cheers, 
kaspar

**Comment by skoneka** [comment]
hi Kaspar, this can be closed . thanks
